name: Model Training & Promotion Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r model_training/requirements.txt

      - name: Run training and promotion scripts
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          python model_training/scripts/train_sentiment.py
          python model_training/scripts/train_summarization.py
          python mlops/promote_models.py
